/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ThButton: typeof import('th-ui')['Button']
    ThInput: typeof import('th-ui')['Input']
  }
}
